"""Added required tables

Revision ID: 38a11af53c1c
Revises: 
Create Date: 2022-06-28 12:01:41.842973

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a11af53c1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('post',
    sa.Column('uid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('owner_uid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['owner_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('token',
    sa.Column('uid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('token', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('user_uid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_token_token'), 'token', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_token'), table_name='token')
    op.drop_table('token')
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###
